# CMake generated Testfile for 
# Source directory: C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson
# Build directory: C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_array "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/test_array")
add_test(test_copy "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/test_copy")
add_test(test_dump "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/test_dump")
add_test(test_dump_callback "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/test_dump_callback")
add_test(test_equal "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/test_equal")
add_test(test_load "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/test_load")
add_test(test_loadb "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/test_loadb")
add_test(test_number "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/test_number")
add_test(test_object "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/test_object")
add_test(test_pack "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/test_pack")
add_test(test_simple "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/test_simple")
add_test(test_unpack "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/test_unpack")
add_test(valid__complex-array "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/complex-array")
add_test(valid__complex-array__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/complex-array")
add_test(valid__empty-array "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/empty-array")
add_test(valid__empty-array__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/empty-array")
add_test(valid__empty-object "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/empty-object")
add_test(valid__empty-object__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/empty-object")
add_test(valid__empty-object-in-array "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/empty-object-in-array")
add_test(valid__empty-object-in-array__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/empty-object-in-array")
add_test(valid__empty-string "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/empty-string")
add_test(valid__empty-string__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/empty-string")
add_test(valid__escaped-utf-control-char "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/escaped-utf-control-char")
add_test(valid__escaped-utf-control-char__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/escaped-utf-control-char")
add_test(valid__false "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/false")
add_test(valid__false__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/false")
add_test(valid__negative-int "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/negative-int")
add_test(valid__negative-int__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/negative-int")
add_test(valid__negative-one "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/negative-one")
add_test(valid__negative-one__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/negative-one")
add_test(valid__negative-zero "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/negative-zero")
add_test(valid__negative-zero__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/negative-zero")
add_test(valid__null "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/null")
add_test(valid__null__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/null")
add_test(valid__one-byte-utf-8 "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/one-byte-utf-8")
add_test(valid__one-byte-utf-8__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/one-byte-utf-8")
add_test(valid__real-capital-e "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/real-capital-e")
add_test(valid__real-capital-e__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/real-capital-e")
add_test(valid__real-capital-e-negative-exponent "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/real-capital-e-negative-exponent")
add_test(valid__real-capital-e-negative-exponent__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/real-capital-e-negative-exponent")
add_test(valid__real-capital-e-positive-exponent "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/real-capital-e-positive-exponent")
add_test(valid__real-capital-e-positive-exponent__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/real-capital-e-positive-exponent")
add_test(valid__real-exponent "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/real-exponent")
add_test(valid__real-exponent__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/real-exponent")
add_test(valid__real-fraction-exponent "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/real-fraction-exponent")
add_test(valid__real-fraction-exponent__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/real-fraction-exponent")
add_test(valid__real-negative-exponent "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/real-negative-exponent")
add_test(valid__real-negative-exponent__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/real-negative-exponent")
add_test(valid__real-positive-exponent "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/real-positive-exponent")
add_test(valid__real-positive-exponent__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/real-positive-exponent")
add_test(valid__real-subnormal-number "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/real-subnormal-number")
add_test(valid__real-subnormal-number__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/real-subnormal-number")
add_test(valid__real-underflow "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/real-underflow")
add_test(valid__real-underflow__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/real-underflow")
add_test(valid__short-string "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/short-string")
add_test(valid__short-string__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/short-string")
add_test(valid__simple-ascii-string "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/simple-ascii-string")
add_test(valid__simple-ascii-string__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/simple-ascii-string")
add_test(valid__simple-int-0 "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/simple-int-0")
add_test(valid__simple-int-0__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/simple-int-0")
add_test(valid__simple-int-1 "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/simple-int-1")
add_test(valid__simple-int-1__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/simple-int-1")
add_test(valid__simple-int-123 "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/simple-int-123")
add_test(valid__simple-int-123__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/simple-int-123")
add_test(valid__simple-object "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/simple-object")
add_test(valid__simple-object__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/simple-object")
add_test(valid__simple-real "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/simple-real")
add_test(valid__simple-real__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/simple-real")
add_test(valid__string-escapes "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/string-escapes")
add_test(valid__string-escapes__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/string-escapes")
add_test(valid__three-byte-utf-8 "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/three-byte-utf-8")
add_test(valid__three-byte-utf-8__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/three-byte-utf-8")
add_test(valid__true "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/true")
add_test(valid__true__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/true")
add_test(valid__two-byte-utf-8 "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/two-byte-utf-8")
add_test(valid__two-byte-utf-8__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/two-byte-utf-8")
add_test(valid__utf-8-string "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/utf-8-string")
add_test(valid__utf-8-string__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/utf-8-string")
add_test(valid__utf-surrogate-four-byte-encoding "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/utf-surrogate-four-byte-encoding")
add_test(valid__utf-surrogate-four-byte-encoding__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/valid/utf-surrogate-four-byte-encoding")
add_test(invalid__apostrophe "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/apostrophe")
add_test(invalid__apostrophe__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/apostrophe")
add_test(invalid__ascii-unicode-identifier "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/ascii-unicode-identifier")
add_test(invalid__ascii-unicode-identifier__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/ascii-unicode-identifier")
add_test(invalid__brace-comma "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/brace-comma")
add_test(invalid__brace-comma__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/brace-comma")
add_test(invalid__bracket-comma "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/bracket-comma")
add_test(invalid__bracket-comma__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/bracket-comma")
add_test(invalid__bracket-one-comma "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/bracket-one-comma")
add_test(invalid__bracket-one-comma__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/bracket-one-comma")
add_test(invalid__empty "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/empty")
add_test(invalid__empty__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/empty")
add_test(invalid__extra-comma-in-array "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/extra-comma-in-array")
add_test(invalid__extra-comma-in-array__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/extra-comma-in-array")
add_test(invalid__extra-comma-in-multiline-array "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/extra-comma-in-multiline-array")
add_test(invalid__extra-comma-in-multiline-array__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/extra-comma-in-multiline-array")
add_test(invalid__garbage-after-newline "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/garbage-after-newline")
add_test(invalid__garbage-after-newline__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/garbage-after-newline")
add_test(invalid__garbage-at-the-end "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/garbage-at-the-end")
add_test(invalid__garbage-at-the-end__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/garbage-at-the-end")
add_test(invalid__integer-starting-with-zero "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/integer-starting-with-zero")
add_test(invalid__integer-starting-with-zero__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/integer-starting-with-zero")
add_test(invalid__invalid-escape "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/invalid-escape")
add_test(invalid__invalid-escape__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/invalid-escape")
add_test(invalid__invalid-identifier "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/invalid-identifier")
add_test(invalid__invalid-identifier__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/invalid-identifier")
add_test(invalid__invalid-negative-integer "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/invalid-negative-integer")
add_test(invalid__invalid-negative-integer__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/invalid-negative-integer")
add_test(invalid__invalid-negative-real "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/invalid-negative-real")
add_test(invalid__invalid-negative-real__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/invalid-negative-real")
add_test(invalid__invalid-second-surrogate "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/invalid-second-surrogate")
add_test(invalid__invalid-second-surrogate__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/invalid-second-surrogate")
add_test(invalid__lone-open-brace "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/lone-open-brace")
add_test(invalid__lone-open-brace__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/lone-open-brace")
add_test(invalid__lone-open-bracket "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/lone-open-bracket")
add_test(invalid__lone-open-bracket__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/lone-open-bracket")
add_test(invalid__lone-second-surrogate "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/lone-second-surrogate")
add_test(invalid__lone-second-surrogate__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/lone-second-surrogate")
add_test(invalid__minus-sign-without-number "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/minus-sign-without-number")
add_test(invalid__minus-sign-without-number__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/minus-sign-without-number")
add_test(invalid__negative-integer-starting-with-zero "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/negative-integer-starting-with-zero")
add_test(invalid__negative-integer-starting-with-zero__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/negative-integer-starting-with-zero")
add_test(invalid__null "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/null")
add_test(invalid__null__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/null")
add_test(invalid__null-byte-in-object-key "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/null-byte-in-object-key")
add_test(invalid__null-byte-in-object-key__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/null-byte-in-object-key")
add_test(invalid__null-byte-in-string "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/null-byte-in-string")
add_test(invalid__null-byte-outside-string "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/null-byte-outside-string")
add_test(invalid__object-apostrophes "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/object-apostrophes")
add_test(invalid__object-apostrophes__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/object-apostrophes")
add_test(invalid__object-garbage-at-end "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/object-garbage-at-end")
add_test(invalid__object-garbage-at-end__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/object-garbage-at-end")
add_test(invalid__object-in-unterminated-array "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/object-in-unterminated-array")
add_test(invalid__object-in-unterminated-array__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/object-in-unterminated-array")
add_test(invalid__object-no-colon "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/object-no-colon")
add_test(invalid__object-no-colon__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/object-no-colon")
add_test(invalid__object-no-value "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/object-no-value")
add_test(invalid__object-no-value__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/object-no-value")
add_test(invalid__object-unterminated-value "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/object-unterminated-value")
add_test(invalid__object-unterminated-value__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/object-unterminated-value")
add_test(invalid__real-garbage-after-e "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/real-garbage-after-e")
add_test(invalid__real-garbage-after-e__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/real-garbage-after-e")
add_test(invalid__real-negative-overflow "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/real-negative-overflow")
add_test(invalid__real-negative-overflow__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/real-negative-overflow")
add_test(invalid__real-positive-overflow "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/real-positive-overflow")
add_test(invalid__real-positive-overflow__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/real-positive-overflow")
add_test(invalid__real-truncated-at-e "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/real-truncated-at-e")
add_test(invalid__real-truncated-at-e__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/real-truncated-at-e")
add_test(invalid__real-truncated-at-point "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/real-truncated-at-point")
add_test(invalid__real-truncated-at-point__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/real-truncated-at-point")
add_test(invalid__tab-character-in-string "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/tab-character-in-string")
add_test(invalid__tab-character-in-string__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/tab-character-in-string")
add_test(invalid__too-big-negative-integer "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/too-big-negative-integer")
add_test(invalid__too-big-negative-integer__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/too-big-negative-integer")
add_test(invalid__too-big-positive-integer "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/too-big-positive-integer")
add_test(invalid__too-big-positive-integer__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/too-big-positive-integer")
add_test(invalid__truncated-unicode-surrogate "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/truncated-unicode-surrogate")
add_test(invalid__truncated-unicode-surrogate__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/truncated-unicode-surrogate")
add_test(invalid__unicode-identifier "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/unicode-identifier")
add_test(invalid__unicode-identifier__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/unicode-identifier")
add_test(invalid__unterminated-array "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/unterminated-array")
add_test(invalid__unterminated-array__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/unterminated-array")
add_test(invalid__unterminated-array-and-object "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/unterminated-array-and-object")
add_test(invalid__unterminated-array-and-object__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/unterminated-array-and-object")
add_test(invalid__unterminated-empty-key "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/unterminated-empty-key")
add_test(invalid__unterminated-empty-key__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/unterminated-empty-key")
add_test(invalid__unterminated-key "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/unterminated-key")
add_test(invalid__unterminated-key__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/unterminated-key")
add_test(invalid__unterminated-object-and-array "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/unterminated-object-and-array")
add_test(invalid__unterminated-object-and-array__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/unterminated-object-and-array")
add_test(invalid__unterminated-string "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/unterminated-string")
add_test(invalid__unterminated-string__strip "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "--strip" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid/unterminated-string")
add_test(invalid-unicode__encoded-surrogate-half "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid-unicode/encoded-surrogate-half")
add_test(invalid-unicode__invalid-utf-8-after-backslash "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid-unicode/invalid-utf-8-after-backslash")
add_test(invalid-unicode__invalid-utf-8-in-array "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid-unicode/invalid-utf-8-in-array")
add_test(invalid-unicode__invalid-utf-8-in-bigger-int "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid-unicode/invalid-utf-8-in-bigger-int")
add_test(invalid-unicode__invalid-utf-8-in-escape "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid-unicode/invalid-utf-8-in-escape")
add_test(invalid-unicode__invalid-utf-8-in-exponent "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid-unicode/invalid-utf-8-in-exponent")
add_test(invalid-unicode__invalid-utf-8-in-identifier "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid-unicode/invalid-utf-8-in-identifier")
add_test(invalid-unicode__invalid-utf-8-in-int "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid-unicode/invalid-utf-8-in-int")
add_test(invalid-unicode__invalid-utf-8-in-real-after-e "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid-unicode/invalid-utf-8-in-real-after-e")
add_test(invalid-unicode__invalid-utf-8-in-string "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid-unicode/invalid-utf-8-in-string")
add_test(invalid-unicode__lone-invalid-utf-8 "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid-unicode/lone-invalid-utf-8")
add_test(invalid-unicode__lone-utf-8-continuation-byte "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid-unicode/lone-utf-8-continuation-byte")
add_test(invalid-unicode__not-in-unicode-range "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid-unicode/not-in-unicode-range")
add_test(invalid-unicode__overlong-3-byte-encoding "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid-unicode/overlong-3-byte-encoding")
add_test(invalid-unicode__overlong-4-byte-encoding "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid-unicode/overlong-4-byte-encoding")
add_test(invalid-unicode__overlong-ascii-encoding "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid-unicode/overlong-ascii-encoding")
add_test(invalid-unicode__restricted-utf-8 "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid-unicode/restricted-utf-8")
add_test(invalid-unicode__truncated-utf-8 "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/make/bin/json_process" "C:/Users/z z/Desktop/Antz/antz/sdk/libs/jansson/test/suites/invalid-unicode/truncated-utf-8")
